GET http://localhost:3000/products

###

GET http://localhost:3000/products/2

###
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Attrezzo 1",
  "code": "AT-1",
  "price": 10.5
}