GET http://localhost:3000/products

###

GET http://localhost:3000/products/2

###
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Attrezzo 2",
  "code": "AT-2",
  "price": 15
}

###
DELETE http://localhost:3000/products/4